### ISSUE TITLE
Unable to convert Image into Text

### ISSUE THREAD

**Issue by rajdeep2k1** [zSynctic/Img2Txt#1]
Hi,
Thanks for sharing wonderful project. 
![Screenshot 2024-01-12 111429](https://github.com/zSynctic/Img2Txt/assets/34005424/9802e605-f921-4732-b8ad-092dac784f59)
I am new to python, I am using your project Img2txt, it is unable to convert image into text.
pls see attachment.
Kindly help.
Thank you.
Rajendra

**Comment by Sh-A-Khasanov** [comment]
![Image](https://github.com/user-attachments/assets/360c6577-340b-4975-8d3c-e9728e1ede1e)


manashu koddan foydalanib ko'ring       ``` pip install easyocr ```

**Comment by vinita-00018** [comment]
(venv) PS D:\Img2Txt-main\Code> python main.py        
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\vinita\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "D:\Img2Txt-main\venv\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "D:\Img2Txt-main\Code\main.py", line 215, in ExtractToText
    self.ExtractedTextBox.insert(tkinter.END, txt)
                                              ^^^
NameError: name 'txt' is not defined
(venv) PS D:\Img2Txt-main\Code>
